apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
spec:
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: password
     - name: MYSQL_DATABASE
       value: damaaf
     - name: MYSQL_USER
       value: akd
     - name: MYSQL_PASSWORD
       value: akd
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: pvc
